**PyTorch notes - Set 1**


---




*Tensors*

In [1]:
import torch
import numpy as np

# Initialize a tensor from a list 
data = [[0,1],[2,3]]                    # <class 'list'> 
x = torch.tensor(data)                  # this is a tensor 
print(x, x.dtype, type(x)) 

tensor([[0, 1],
        [2, 3]]) torch.int64 <class 'torch.Tensor'>


In [ ]:
# ... as we initialize numpy array from a list
x_np = np.array(data)
print(x_np,x_np.dtype,type(x_np))

In [ ]:
# You can convert a numpy array to tensor and vice versa
x = torch.from_numpy(x_np)
print(x, x.dtype, type(x))

t = torch.ones((3,2),dtype=torch.float32)
print(t, t.dtype, type(t))
t_np = t.numpy() 
print(t_np, t_np.dtype, type(t_np))

In [ ]:
# You can define the shape of a tensor
shape = (2)
x_rand = torch.rand(shape)                    # it is 1D vector
print(x_rand,x_rand.shape)

x_rand_reshaped = x_rand.reshape(-1,1)        # reshape to a *2D* column vector
print(x_rand_reshaped,x_rand_reshaped.shape)

shape = (2,1)
x_rand = torch.rand(shape)
print(x_rand,x_rand.shape)

shape = (2,3,4)
x_rand = torch.rand(shape)
print(x_rand,x_rand.shape)

In [4]:
# Change the shape of a tensor
x_rand = torch.rand([4000,28,28])
y1 = x_rand.view(x_rand.size(0),1,28,28)
print(y1.shape)
#print(y1.size())
y2 = x_rand.view(x_rand.size(0),-1)
print(y2.shape)

torch.Size([4000, 1, 28, 28])
torch.Size([4000, 1, 28, 28])
torch.Size([4000, 784])


In [15]:
# Check out the dimensions of the following

x_seq = torch.tensor( 1.0 )
print('torch.tensor( 1.0 ) >>',x_seq.shape) # 0 dimension

#x_seq = torch.tensor( 1.0, 1.0 ) #ERROR! tensor takes 1 arg.
#print(x_seq.shape)

x_seq = torch.tensor( [1.0] )
print('torch.tensor([ 1.0 ]) >>', x_seq.shape) # 1 dimension, size 1

x_seq = torch.tensor( [1.0, 1.0] )
print('torch.tensor([ 1.0, 1.0 ]) >>',x_seq.shape) # 1 dimension, size 2

x_seq = torch.tensor([ [1.0] ]) # putting a second bracket adds another dim.
print('torch.tensor([ [1.0] ]) >>', x_seq.shape) # 2 dimension, each size 1

x_seq = torch.tensor([ [1.0], [1.0] ])
print('torch.tensor([ [1.0], [1.0] ]) >>', x_seq.shape)

x_seq = torch.tensor([ [1.0, 1.0] ])
print('torch.tensor([ [1.0, 1.0] ]) >>', x_seq.shape)

x_seq = torch.tensor( [ [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ] ] )
print(x_seq.shape)

x_seq = torch.tensor([ 
    [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ] 
])
print(x_seq.shape)

x_seq = torch.tensor([ 
    [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ],
    [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ] 
])
print(x_seq.shape)


torch.tensor( 1.0 ) >> torch.Size([])
torch.tensor([ 1.0 ]) >> torch.Size([1])
torch.tensor([ 1.0, 1.0 ]) >> torch.Size([2])
torch.tensor([ [1.0] ]) >> torch.Size([1, 1])
torch.tensor([ [1.0], [1.0] ]) >> torch.Size([2, 1])
torch.tensor([ [1.0, 1.0] ]) >> torch.Size([1, 2])
torch.Size([1, 2, 5])
torch.Size([1, 2, 5])
torch.Size([2, 2, 5])


In [ ]:
# You can slice a tensor
x_rand = torch.rand((2,3))
print(x_rand)
print(f"First row: {x_rand[0]}")
print(f"First row: {x_rand[0,:]}")
print(f"First column: {x_rand[:, 0]}")
print(f"Last column: {x_rand[:, -1]}")
print(f"A slice: {x_rand[0:2, 0:2]}")
print(f"A detached element: {x_rand[0,0].item()}")

In [14]:
# Slice at higher dimensions
x_seq = torch.randn(1,3,5)
print(x_seq.shape)

print(x_seq)

# At the first time instant, the feature vector is
print(x_seq[0,0,:])

# At the second time instant, the feature vector is
print(x_seq[0,1,:])

torch.Size([1, 3, 5])
tensor([[[-0.7981,  1.1100,  2.1945,  0.8437,  0.6368],
         [ 0.1701, -0.5426, -0.0547, -0.8019, -0.7363],
         [ 0.0026, -0.4802, -2.6052,  0.6449,  0.8568]]])
tensor([-0.7981,  1.1100,  2.1945,  0.8437,  0.6368])
tensor([ 0.1701, -0.5426, -0.0547, -0.8019, -0.7363])


In [ ]:
# Concatenate tensors
t = torch.ones((1,2))
t1 = torch.cat([t, t, t],dim=1)   # horizontally
print(t1)
t2 = torch.cat([t, t, t],dim=0)   # vertically
print(t2)

In [ ]:
# Arithmetic operations
t1 = torch.ones((1,2))

# - matrix multiplication
y1 = t1 @ t1.T
print(y1)
y2 = t1.matmul(t1.T)
print(y2)

# - element-wise multiplication
z1 = t1 * t1
print(z1)
z2 = t1.mul(t1)
print(z2)

*Tensors as a form of computational graph* 

In [ ]:
# A tensor does not require gradient calculation by default
x = torch.tensor(1.0)
print(x.requires_grad)
print(x)

# You can set gradient calculation to true
w = torch.tensor(0.5, requires_grad=True) 
print(w)

# Some attributes of a tensor
print('w.data:',w.data)
print('w.grad:',w.grad)
print('w.requires_grad:',w.requires_grad)
print('w.grad_fn:',w.grad_fn)
print('w.is_leaf:',w.is_leaf)

In [ ]:
# Let's create a simple graph
a = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(3.0,requires_grad=True)

print('a.data:',a.data)
print('a.grad:',a.grad)
print('a.requires_grad:',a.requires_grad)
print('a.grad_fn:',a.grad_fn)
print('a.is_leaf:',a.is_leaf)

print('')

# A function of at least a tensor
c = 2 * a
print('c.data:',c.data)
print('c.grad:',c.grad)   # grad is no longer held because it is not a leaf node
print('c.requires_grad:',c.requires_grad)
print('c.grad_fn:',c.grad_fn)
print('c.is_leaf:',c.is_leaf)

print('')

# backward pass and then check out the leaf tensor
c.backward()
print('a.data:',a.data)
print('a.grad:',a.grad)
print('a.requires_grad:',a.requires_grad)
print('a.grad_fn:',a.grad_fn)
print('a.is_leaf:',a.is_leaf)


In [ ]:
# A larger graph...
a = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(3.0,requires_grad=False)

c = a * b
d = a + c

print('a.data:',a.data)
print('a.grad:',a.grad)
print('a.requires_grad:',a.requires_grad)
print('a.grad_fn:',a.grad_fn)
print('a.is_leaf:',a.is_leaf)

print('')
print('c.data:',c.data)
print('c.grad:',c.grad)   
print('c.requires_grad:',c.requires_grad)
print('c.grad_fn:',c.grad_fn)
print('c.is_leaf:',c.is_leaf)

print('')
print('d.data:',d.data)
print('d.grad:',d.grad)   
print('d.requires_grad:',d.requires_grad)
print('d.grad_fn:',d.grad_fn)
print('d.is_leaf:',d.is_leaf)

print('')
print('After backward pass...')
d.backward()  # grads for all tensors with requires_grad=True are calculated
              #   except for grads for tensors that are not leaf.
print('a.data:',a.data)
print('a.grad:',a.grad)
print('a.requires_grad:',a.requires_grad)
print('a.grad_fn:',a.grad_fn)
print('a.is_leaf:',a.is_leaf)

print('')
print('b.data:',b.data)
print('b.grad:',b.grad)
print('b.requires_grad:',b.requires_grad)
print('b.grad_fn:',b.grad_fn)
print('b.is_leaf:',b.is_leaf)

print('')
print('c.data:',c.data)
print('c.grad:',c.grad)     # gradient is not stored since it is not a leaf node
print('c.requires_grad:',c.requires_grad)
print('c.grad_fn:',c.grad_fn)
print('c.is_leaf:',c.is_leaf)


In [ ]:
# Let's solve for w in y = w * x, where y and x are given below
y = torch.tensor(2.0)
x = torch.tensor(1.0)

w = torch.tensor(0.5, requires_grad=True)
print('w before update:',w)

# Try the following for more than 1 iteration
for iter in range(1):
  # forward pass
  y_hat = w * x
  print('y_hat:',y_hat)  # this is a result of an operation, so there is grad_fn

  # calculate loss
  loss = (y_hat-y) **2
  print('loss:',loss)    # this is a result of an operation, so there is grad_fn

  # backward pass 
  #   - for all tensors with requires_grad, the gradients will be calculated
  print('Gradient before back. pass:',w.grad)
  loss.backward()                             # gradient of loss = -2*(y_hat-y)
  print('Gradient after back. pass:',w.grad)

  #w.grad.zero_()

  #print(w)

  # update w
  #   If you do the below without torch.no_grad(), you will get an error:
  #     TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
  #   This is because updating makes it an "intermediate" (non-leaf) tensor,
  #     which makes it grad type None and requires_grad becomes False.
  #     So, in torch.no_grad() context; thus autograd is disabled 
  #       https://www.youtube.com/watch?v=MswxJw-8PvE
  with torch.no_grad():
    w -= 0.1 * w.grad # in-place operation

  print('w after update:',w)
  print('Gradient after update:',w.grad)

  # Zero the gradient - Gradients accumulate in tensors, so zero them.
  w.grad.zero_()

# Note the difference between torch.eval() and torch.no_grad()
#   torch.eval(): all the layers will be in eval mode, including the  
#                 batchnorm and dropout layers
#   torch.no_grad(): deactivate the autograd engine


*Datasets from PyTorch*

In [ ]:
# There are prepared datasets for vision, text and audio
from torchvision import datasets
from torchvision import transforms
from matplotlib import pyplot as plt

# Create a transform to be applied to each sample
#   .ToTensor() is critical; without it, dataloader will give error!
transform1 = transforms.Compose([
    transforms.ToTensor(),  # converts PIL image or numpy array (HxWxC) into a 
                            #   torch.FloatTensor (CxHxW), scales it to [0,1] 
    transforms.Normalize(mean=[0.5],std=[0.5]) # for 1 channel
                            #   [0.5,0.5,0.5] for 3 channels
                            # Conversion from RGB to gray could also be useful
                            # Transforms can also be added to the dataloader
    ])

# Download the dataset and apply the transform for each sample
train_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform = transform1
    )

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform = transform1
    )

print(train_data.data.shape) 
print(train_data.targets.shape)

sample_id = 0
image = train_data.data[sample_id]
label = train_data.targets[sample_id]

print(type(image),image.shape, image[20,20]) 
# print(type(label),label.shape)

plt.imshow(image, cmap="gray") # .squeeze() if img.shape is (1,28,28)
plt.title(label)


*Dataloader*

In [ ]:
from torch.utils.data import DataLoader #creates an iterable around a dataset

batch_size = 64

train_dataloader = DataLoader(train_data,batch_size,shuffle=True)
test_dataloader = DataLoader(test_data,batch_size,shuffle=False)

# Working with a dataloader
for X,y in train_dataloader:
  print(X.shape) #batchsize, number of channels, height, width
  print(y.shape) #batchsize
  break # one run of the dataloader

sample_id = 0
image = X[sample_id,:,:,:]
label = y[sample_id]

#print(image.shape) # torch.Size([1, 28, 28])

plt.imshow(image.squeeze(), cmap="gray") # we squeeze because shape is (1,28,28)
plt.title(label)

# visualize the batch of the dataset
import torchvision
# X is of size (b,c,h,w)
grid = torchvision.utils.make_grid(X,nrow=10) # grid is a tensor of size (c,h,w)
                                              # nrow: number of imgs in each row
transform_tensor_to_PIL = transforms.ToPILImage() 
grid_img = transform_tensor_to_PIL(grid)      # (h,w,c)
plt.imshow(grid_img)


*Datasets from numpy arrays*

In [ ]:
# Let's download a dataset from sklearn
from sklearn.datasets import load_digits
digits = load_digits()

#print(digits.images.shape)  # (1797, 8, 8)
#print(type(digits.images))  # <class 'numpy.ndarray'>

# Let's do train - test split
X = digits.images
y = digits.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                    test_size=0.20,
                                                    shuffle=True)

# First, transform numpy to tensor
# X_train is of size (batch,h,w). Convert it to (b,c,h,w)
X_train = torch.tensor(X_train).unsqueeze(1)
X_test = torch.tensor(X_test).unsqueeze(1)

y_train = torch.tensor(y_train)
y_test = torch.tensor(y_test)


*Create a custom dataset from tensors*

In [ ]:
# We do this by using TensorDataset
from torch.utils.data import TensorDatasethange SGD to Adam, we simply change optim.SGD to optim.Adam, also note how we do not have to provide an initial learning rate for Adam as PyTorch specifies a sensibile default initia

# Second, convert the tensors to dataset
train_data = TensorDataset(X_train,y_train)
test_data = TensorDataset(X_test,y_test)

# Create the dataloaders
train_dataloader = DataLoader(train_data, batch_size=128, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=1, shuffle=False)

# Working with a dataloader
for X,y in train_dataloader:
  print(X.shape) #batchsize, number of channels, height, width
  print(y.shape) #batchsize
  break # one run of the dataloader

# Alternatively, ...
X, y = next(iter(train_dataloader))
print(X.shape)
print(y.shape)

# Visualize
grid = torchvision.utils.make_grid(X,nrow=16) # grid is a tensor of size (c,h,w)
                                              # nrow: number of imgs in each row
transform_tensor_to_PIL = transforms.ToPILImage() 
grid_img = transform_tensor_to_PIL(grid)      # (h,w,c)
plt.imshow(grid_img)


*Create a custom dataset from image files*

In [ ]:
# We do this by writing a Dataset class 
import os
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchvision.io import read_image
from torchvision.transforms import transforms
from skimage import io

# we need a folder with images
# we need a csv or txt annotation file with image filenames and labels, e.g.:
#   img1.jpg, 0
#   img2.jpg, 0
#   img3.jpg, 1
#   ...

class CustomImageDataset(Dataset):
  def __init__(self,annotation_file, img_dir, transform=None, target_transform=None):
    self.images_labels_df = pd.read_csv(annotation_file, 
                                        header=None, 
                                        names=["Image name", "Label"])
    self.img_dir = img_dir
    self.transform = transform
    self.target_transform = target_transform
  
  def __len__(self):
    return len(self.images_labels_df)
  
  def __getitem__(self,idx):
    #iloc indexed location, 0 is filename, 1 is target label
    img_path = os.path.join(self.img_dir, self.images_labels_df.iloc[idx,0]) 
    image = read_image(img_path) # this produces tensor of size c,h,w
    #image = io.imread(img_path) # if used, transform w/ transforms.ToTensor()

    # do not forget to convert the label to torch tensor as well
    label = torch.tensor((self.images_labels_df.iloc[idx,1])) 
    
    if self.transform:
      image = self.transform(image)
    
    if self.target_transform:
      label = self.target_transform(label)

    return image, label


# Let's now check it out

# Directory and annotation file
img_dir = './sample_data/images/'
annotation_file = './sample_data/images/labels.txt'

# Create the custom dataset
custom_dataset = CustomImageDataset(annotation_file=annotation_file, 
                                    img_dir=img_dir, 
                                    transform=None)  

# Create the dataloader
dataloader = DataLoader(dataset=custom_dataset,batch_size=1)

# Check it out
X, y = next(iter(dataloader))
print(X.shape)
print(y.shape)




torch.Size([1, 3, 2048, 2048])
torch.Size([1])
