**Tensors**


---




*Basics*

In [3]:
import torch
import numpy as np

# Initialize a tensor from a list 
data = [[0,1],[2,3]]                    # <class 'list'> 
x = torch.tensor(data)                  # this is a tensor 
print(x, x.dtype, type(x)) 

tensor([[0, 1],
        [2, 3]]) torch.int64 <class 'torch.Tensor'>


In [ ]:
# Initialize numpy array from a list
x_np = np.array(data)
print(x_np,x_np.dtype,type(x_np))

In [ ]:
# You can convert a numpy array to tensor and vice versa
x = torch.from_numpy(x_np)
print(x, x.dtype, type(x))

t = torch.ones((3,2),dtype=torch.float32)
print(t, t.dtype, type(t))
t_np = t.numpy() 
print(t_np, t_np.dtype, type(t_np))

In [ ]:
# Dimension and size of a tensor

print("# This is a 1D tensor - 1 dimension, size 1")
shape = (1)
x_rand = torch.rand(shape)                    
print(x_rand,x_rand.shape)

print("# This is also a 1D tensor - 1 dimension, size 2")
shape = (2)
x_rand = torch.rand(shape)                    
print(x_rand,x_rand.shape)

print("# Reshape to a 2D row tensor")
x_rand_reshaped = x_rand.reshape(1,-1)        # 1 row
print(x_rand_reshaped,x_rand_reshaped.shape)

print("# Reshape to a 2D column tensor")
x_rand_reshaped = x_rand.reshape(-1,1)        
print(x_rand_reshaped,x_rand_reshaped.shape)

print("# 2D tensor of size (2,1)")
shape = (2,1)
x_rand = torch.rand(shape)
print(x_rand,x_rand.shape)

print("# 3D tensor")
shape = (2,3,4)
x_rand = torch.rand(shape)
print(x_rand,x_rand.shape)

print("# 4D tensor")
shape = (1,2,3,4)
x_rand = torch.rand(shape)
print(x_rand,x_rand.shape)

In [9]:
# Change the shape of a tensor - adding another dimension
x_rand = torch.rand([4000,28,28])
y1 = x_rand.view(x_rand.size(0),1,28,28)
print(y1.shape)
#print(y1.size())   # Instead of .shape, you can use .size()

# Change the shape of a tensor - flattening 
y2 = x_rand.view(x_rand.size(0),-1)
print(y2.size())

torch.Size([4000, 1, 28, 28])
torch.Size([4000, 784])


In [8]:
# Check out the dimensions of the following

x_seq = torch.tensor( 1.0 )
print('torch.tensor( 1.0 ) >>', x_seq.shape) # 0 dimension

#x_seq = torch.tensor( 1.0, 1.0 ) #ERROR! tensor takes 1 arg.
#print(x_seq.shape)

x_seq = torch.tensor( [1.0] )
print('torch.tensor([ 1.0 ]) >>', x_seq.shape) # 1 dimension, size 1

x_seq = torch.tensor( [1.0, 1.0] )
print('torch.tensor([ 1.0, 1.0 ]) >>',x_seq.shape) # 1 dimension, size 2

x_seq = torch.tensor([ [1.0] ]) # putting a second bracket adds another dim.
print('torch.tensor([ [1.0] ]) >>', x_seq.shape) # 2 dimension, each size 1

x_seq = torch.tensor([ [1.0], [1.0] ])
print('torch.tensor([ [1.0], [1.0] ]) >>', x_seq.shape)

x_seq = torch.tensor([ [1.0, 1.0] ])
print('torch.tensor([ [1.0, 1.0] ]) >>', x_seq.shape)

x_seq = torch.tensor( [ [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ] ] )
print(x_seq.shape)

x_seq = torch.tensor([ 
    [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ] 
])
print(x_seq.shape)

x_seq = torch.tensor([ 
    [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ],
    [ [1.0,1.0,1.0,1.0,1.0], [1.0,1.0,1.0,1.0,1.0] ] 
])
print(x_seq.shape)


torch.tensor( 1.0 ) >> torch.Size([])
torch.tensor([ 1.0 ]) >> torch.Size([1])
torch.tensor([ 1.0, 1.0 ]) >> torch.Size([2])
torch.tensor([ [1.0] ]) >> torch.Size([1, 1])
torch.tensor([ [1.0], [1.0] ]) >> torch.Size([2, 1])
torch.tensor([ [1.0, 1.0] ]) >> torch.Size([1, 2])
torch.Size([1, 2, 5])
torch.Size([1, 2, 5])
torch.Size([2, 2, 5])


In [9]:
# You can slice a tensor
x_rand = torch.rand((2,3))
print(x_rand)
print(f"First row: {x_rand[0]}")
print(f"First row: {x_rand[0,:]}")
print(f"First column: {x_rand[:, 0]}")
print(f"Last column: {x_rand[:, -1]}")
print(f"A slice: {x_rand[0:2, 0:2]}")
print(f"A detached element: {x_rand[0,0].item()}")

tensor([[0.5920, 0.6750, 0.9945],
        [0.3830, 0.3742, 0.1446]])
First row: tensor([0.5920, 0.6750, 0.9945])
First row: tensor([0.5920, 0.6750, 0.9945])
First column: tensor([0.5920, 0.3830])
Last column: tensor([0.9945, 0.1446])
A slice: tensor([[0.5920, 0.6750],
        [0.3830, 0.3742]])
A detached element: 0.592011570930481


In [10]:
# Slice at higher dimensions
x_seq = torch.randn(1,3,5)
print(x_seq.shape)

print(x_seq)

# At the first time instant, the feature vector is
print(x_seq[0,0,:])

# At the second time instant, the feature vector is
print(x_seq[0,1,:])

torch.Size([1, 3, 5])
tensor([[[ 1.6154, -0.1074,  0.6614, -0.4766,  1.0111],
         [-1.4426,  1.5684,  0.1512,  1.4251,  0.6145],
         [ 1.6768,  0.4665,  0.6591, -0.4032, -1.0955]]])
tensor([ 1.6154, -0.1074,  0.6614, -0.4766,  1.0111])
tensor([-1.4426,  1.5684,  0.1512,  1.4251,  0.6145])


In [11]:
# Concatenate tensors
t = torch.ones((1,2))
t1 = torch.cat([t, t, t],dim=1)   # horizontally
print(t1)
t2 = torch.cat([t, t, t],dim=0)   # vertically
print(t2)

tensor([[1., 1., 1., 1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [12]:
# Arithmetic operations
t1 = torch.ones((1,2))

# - matrix multiplication
y1 = t1 @ t1.T
print(y1)
y2 = t1.matmul(t1.T)
print(y2)

# - element-wise multiplication
z1 = t1 * t1
print(z1)
z2 = t1.mul(t1)
print(z2)

tensor([[2.]])
tensor([[2.]])
tensor([[1., 1.]])
tensor([[1., 1.]])
